= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2021/22
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Lena Mareike Wischmann

**Gruppe:** 27

== Was habe ich gelernt / was habe ich nicht gelernt?
Die Nutzung von Frameworks ist etwas, was ich vorher noch nie so gemacht hatte. Auch mit git habe ich zuvor kaum Erfahrungen gemacht, genauso wie Tests für Software zu schreiben. Durch dieses Projekt konnte man sich mit diesen Sachen gut vertraut machen.
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
Die Kommunikation untereinander war gut. Es wurde sich gegenseitig geholfen und alle waren offen für Diskussionen und Vorschläge von Anderen. Durch das Aufteilen in Paare und Domainen hat auch die Arbeitsteilung großteils gut funktioniert. Dadurch, dass ich zufällig in dieses Team hinzugefügt wurde und somit niemanden kannte, aber fast alle anderen sich schon kannten, war es für mich etwas schwer mich mit einzugliedern. Trotzdem lief die Zusammenarbeit gut. 
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
Dadurch, dass ich fast ausschließlich am Pool gearbeitet habe, habe ich mich vergleichsweise recht wenig mit Salespoint auseinandergesetzt. Doch ich habe von meinen Teammitgliedern gehört, dass Salespoint und auch die Dokumentation zu wünschen übrig lassen.
Es war interessant mit Spring Boot zu arbeiten und bei Problemen konnte man meist recht schnell eine Lösung im Internet finden.
Da ich zuvor noch nie mit HTML gearbeitet hatte, war Thymeleaf ziemlich verwirrend für mich, aber man konnte sich nach einer Weile daran gewöhnen. 
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was war gut? Was war verbesserungswürdig?

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
Die Meilensteine sollten nachschlagbar sein, denn unser Tutor hatte teilweise andere Informationen über die Meilensteine als wir, da anscheinend der Plan, der in der Einführungsvorlesung vorgestellt wurde, sich geändert hatte.
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.

== Feedback für den Tutor
Unser Tutor hat uns sehr gut betreut. Er hat die Meetings gut geleitet, die Aufgaben verständlich erklärt, ist auf Fragen eingegangen und war auch flexibel und immer hilfsbereit.
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?

== Sonstiges und Anmerkungen
-
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
