= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2021/22
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von: Jakub Gawroński**

**Gruppe: 27**

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Ich habe einen völlig neuen Arbeitsablauf gelernt. Ich habe noch nie mit so vielen Leuten an einem Projekt gearbeitet, daher war es definitiv eine Herausforderung, alles zu synchronisieren und eine einheitliche Methode für die Umsetzung der Dinge zu finden. Das war am Anfang definitiv ein Problem, da wir alle unterschiedliche Programmierhintergründe und ein unterschiedliches Maß an Frontend-/Backend-Technologien hatten, sodass wir manchmal lange diskutieren mussten.

Ich habe auf jeden Fall ein neues Framework gelernt, Spring. Ich finde nicht, dass es mein Favorit ist, aber es ist definitiv eine gute Ergänzung zu meinen Fähigkeiten. Außerdem habe ich definitiv mehr über die Backend-Entwicklung und Dinge wie Requests, Datenbanken und vieles mehr gelernt.


== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Da ich der SCRUM-Master war, waren die Aspekte der Teamarbeit für mich definitiv etwas anders. Ich fühlte mich während des gesamten Projekts sehr unter Druck, da ich immer kontrollieren musste, ob alles nach Plan lief, was nicht so einfach war. Die meisten von uns in der Gruppe sind gute Freunde, so dass ich manchmal das Gefühl hatte, nicht genug Autorität zu haben, um den Diskussionsprozess einfach zu überspringen und mich sofort für eine Idee zu entscheiden, was manchmal notwendig war, da die Zeit drängte.

Aber abgesehen davon liefen die Dinge ziemlich reibungslos, wir haben gut kommuniziert und die meisten Aufgaben wurden rechtzeitig erledigt.

Wir waren auch eine sehr internationale Gruppe, sodass die Sprachbarriere auch sichtbar war.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Für unser Projekt war Salespoint nicht so wichtig. Wir haben es nur für Zeit implementierung benutzt und Users, also hier kann ich nicht viel sagen.

Thymeleaf habe ich nicht so gut gefunden. Für mich der ganze Workflow war nicht intuitiv vor allem am Anfang. Ich verstehe es jetzt schon aber ich finde es nicht so gut wie React oder Angular.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Meiner Meinung nach sollen die Gruppen so Groß bleiben wie sie jetzt waren (8 Leute) ich denke das mann kann die Teamarbeit besser strukturieren z.B. 2 kleiner Teams von 4 Leuten, mit zwei Gruppenleiter - eine von diese wird ein SCRUM-Master.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Ja. Felix war immer sehr hilfreich, hat uns alles sehr gut erklärt und hat immer jeder unsere Frage beantwortet.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
Nein